// Auto-generated by scripts/extract-colors.ts
// Run: bun run extract-colors

export const imageColors: Record<string, string[]> = {
  "meetingbot": [
    "#5367c6",
    "#626fb7"
  ],
  "meetingnotes": [
    "#53acc6",
    "#c6a553",
    "#c5a654"
  ],
  "gitreadme.dev": [
    "#c69b53",
    "#c6ad53"
  ],
  "habits together": [
    "#c68753",
    "#5382c6",
    "#c29357"
  ],
  "onus ai": [
    "#6753c6",
    "#5778c2",
    "#915ebb"
  ],
  "(a)intern": [
    "#c66f53",
    "#bb5d6e",
    "#b86860"
  ],
  "symphony": [
    "#c68e53",
    "#c18957",
    "#b38066"
  ],
  "hackmate": [
    "#53c6c6",
    "#5b99be",
    "#5eadbb"
  ],
  "mattausgretzinger.com": [
    "#c6ac53",
    "#c6a253",
    "#af9d69"
  ],
  "wedding photos": [
    "#888888",
    "#666666"
  ],
  "valentines game": [
    "#c55f54",
    "#c16257",
    "#c16257"
  ],
  "monkey mind": [
    "#c6a253",
    "#c65f53",
    "#c29b57"
  ],
  "simple terms": [
    "#888888",
    "#666666"
  ],
  "room booking system": [
    "#c65358",
    "#bc5c5d",
    "#a77174"
  ],
  "personal website v1": [
    "#c66c53",
    "#53a3c6",
    "#c37655"
  ],
  "server insights": [
    "#53aec6",
    "#53adc6",
    "#c66e53"
  ],
  "triangle ball": [
    "#53a2c6",
    "#539ac6",
    "#539fc6"
  ],
  "html resume template": [
    "#888888",
    "#666666"
  ],
  "multiplayer clock": [
    "#5380c6",
    "#8d53c6",
    "#53c6a8"
  ],
  "tempestuous turrets": [
    "#c68853",
    "#c69053",
    "#b38a65"
  ],
  "binary 0101": [
    "#64b5b1",
    "#66b37d",
    "#68b1a3"
  ],
  "smiley face game": [
    "#888888",
    "#666666"
  ],
  "boulder buddies": [
    "#c6c653",
    "#a7a072",
    "#8479a0"
  ],
  "hide and seek": [
    "#888888",
    "#666666"
  ],
  "fall car": [
    "#53c66e",
    "#bdc653",
    "#53c654"
  ],
  "boardy": [
    "#c69c53",
    "#5398c6",
    "#c17857"
  ],
  "mcmaster university": [
    "#c6538c",
    "#c69b53",
    "#c66c53"
  ],
  "rbc amplify": [
    "#538ec6",
    "#c6b653",
    "#5394c6"
  ],
  "mcmaster engineering society": [
    "#c2566e",
    "#b76172",
    "#a37582"
  ],
  "deltahacks": [
    "#c6a953",
    "#5396c6",
    "#c65353"
  ],
  "arctic wolf": [
    "#5397c6",
    "#5397c6",
    "#6e89ab"
  ]
};
